// GENERATED by tools/extract_sf_stats.py -- do not edit by hand.
// Source: "Star Force Enhancement_Stat Tables - MapleStory Wiki.htm" (MapleStory Wiki, Delta Values tables).
//
// Per-star stat gain, indexed [star][bracketIndex]. Use sfBracket(level) for the
// index. Keys absent from a star's entry are zero for every bracket.
//
//   stat        gain applied to EACH class-relevant stat. A mage gets this on
//               both INT and LUK, so its value is stat * (w_main + w_sub) --
//               it is NOT a single total.
//   att/matt    flat attack gain. Below 16* on weapons this is a {mul, add}
//               formula over the weapon's own base attack:
//               gain = floor(base * mul + add).
//   glovesAtt   slot-conditional: applies only to gloves.
//
// From 23* up there is no class stat at all -- the gain is pure attack.
// DEF, Max HP, Speed and Jump are dropped as combat-irrelevant here.
//
// The weapon table has no level-250 column, so SF_CAP_WEAPON's last entry
// repeats the 200-249 column. Moot in practice: the endgame weapon arrives at
// 22* with its remaining stars granted by quests, not bought with meso.

const SF_BRACKETS = [
  { label:"128-137", min:128, max:137 },
  { label:"138-149", min:138, max:149 },
  { label:"150-159", min:150, max:159 },
  { label:"160-199", min:160, max:199 },
  { label:"200-249", min:200, max:249 },
  { label:"250", min:250, max:250 },
];

// bracket index for an item level, or -1 if below the table
function sfBracket(level) {
  for (let i = 0; i < SF_BRACKETS.length; i++) {
    if (level >= SF_BRACKETS[i].min && level <= SF_BRACKETS[i].max) return i;
  }
  return level > 250 ? SF_BRACKETS.length - 1 : -1;
}

// max reachable star per bracket, derived from where the wiki cells go blank
const SF_CAP_WEAPON = [20,25,25,25,25,25];
const SF_CAP_ARMOR  = [20,30,30,30,30,30];


// Weapons.
const SF_STATS_WEAPON = {
  1: { stat:[2,2,2,2,2], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  2: { stat:[2,2,2,2,2], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  3: { stat:[2,2,2,2,2], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  4: { stat:[2,2,2,2,2], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  5: { stat:[2,2,2,2,2], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  6: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  7: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  8: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  9: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  10: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  11: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  12: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  13: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  14: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  15: { stat:[3,3,3,3,3], att:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}], matt:[{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1},{mul:0.02,add:1}] },
  16: { stat:[7,9,11,13,15], att:[6,7,8,9,13], matt:[6,7,8,9,13] },
  17: { stat:[7,9,11,13,15], att:[6,7,8,9,13], matt:[6,7,8,9,13] },
  18: { stat:[7,9,11,13,15], att:[7,8,9,10,14], matt:[7,8,9,10,14] },
  19: { stat:[7,9,11,13,15], att:[8,9,10,11,14], matt:[8,9,10,11,14] },
  20: { stat:[7,9,11,13,15], att:[9,10,11,12,15], matt:[9,10,11,12,15] },
  21: { stat:[0,9,11,13,15], att:[0,11,12,13,16], matt:[0,11,12,13,16] },
  22: { stat:[0,9,11,13,15], att:[0,12,13,14,17], matt:[0,12,13,14,17] },
  23: { att:[0,30,31,32,34], matt:[0,30,31,32,34] },
  24: { att:[0,31,32,33,35], matt:[0,31,32,33,35] },
  25: { att:[0,32,33,34,36], matt:[0,32,33,34,36] },
};

// Armor & accessories.
const SF_STATS_ARMOR = {
  1: { stat:[2,2,2,2,2,2] },
  2: { stat:[2,2,2,2,2,2] },
  3: { stat:[2,2,2,2,2,2] },
  4: { stat:[2,2,2,2,2,2] },
  5: { stat:[2,2,2,2,2,2], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  6: { stat:[3,3,3,3,3,3] },
  7: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  8: { stat:[3,3,3,3,3,3] },
  9: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  10: { stat:[3,3,3,3,3,3] },
  11: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  12: { stat:[3,3,3,3,3,3] },
  13: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  14: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  15: { stat:[3,3,3,3,3,3], glovesAtt:[1,1,1,1,1,1], glovesMatt:[1,1,1,1,1,1] },
  16: { stat:[7,9,11,13,15,17], att:[7,8,9,10,12,14], matt:[7,8,9,10,12,14] },
  17: { stat:[7,9,11,13,15,17], att:[8,9,10,11,13,15], matt:[8,9,10,11,13,15] },
  18: { stat:[7,9,11,13,15,17], att:[9,10,11,12,14,16], matt:[9,10,11,12,14,16] },
  19: { stat:[7,9,11,13,15,17], att:[10,11,12,13,15,17], matt:[10,11,12,13,15,17] },
  20: { stat:[7,9,11,13,15,17], att:[11,12,13,14,16,18], matt:[11,12,13,14,16,18] },
  21: { stat:[0,9,11,13,15,17], att:[0,13,14,15,17,19], matt:[0,13,14,15,17,19] },
  22: { stat:[0,9,11,13,15,17], att:[0,15,16,17,19,21], matt:[0,15,16,17,19,21] },
  23: { att:[0,17,18,19,21,23], matt:[0,17,18,19,21,23] },
  24: { att:[0,19,20,21,23,25], matt:[0,19,20,21,23,25] },
  25: { att:[0,21,22,23,25,27], matt:[0,21,22,23,25,27] },
  26: { att:[0,22,23,24,26,28], matt:[0,22,23,24,26,28] },
  27: { att:[0,23,24,25,27,29], matt:[0,23,24,25,27,29] },
  28: { att:[0,24,25,26,28,30], matt:[0,24,25,26,28,30] },
  29: { att:[0,25,26,27,29,31], matt:[0,25,26,27,29,31] },
  30: { att:[0,26,27,28,30,32], matt:[0,26,27,28,30,32] },
};

